"""add category

Revision ID: 2898197ecc21
Revises: b33b7ee0fd9a
Create Date: 2021-08-22 21:01:51.823661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2898197ecc21'
down_revision = 'b33b7ee0fd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
